[tool.poetry]
name = "django-chatbot"
version = "0.1.0"
description = ""
authors = ["Bipin Mishra <bipin.mishra@atlascopco.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
